package ad_db4o;
// Generated 10-ene-2019 13:29:24 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int codEmpleado;
     private String nombre;
     private String apellido;
     private String puesto;
     private int salario;

    public Empleado() {
    }

	
    public Empleado(int codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public Empleado(int codEmpleado, String nombre, String apellido, String puesto, int salario) {
       this.codEmpleado = codEmpleado;
       this.nombre = nombre;
       this.apellido = apellido;
       this.puesto = puesto;
       this.salario = salario;
    }
   
    public int getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(int codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellidos) {
        this.apellido = apellidos;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }




}


